tunnel: 83ce6d44-645f-4e7e-86ac-1fdbd08ebf4b
credentials-file: /home/umbrel/.cloudflared/83ce6d44-645f-4e7e-86ac-1fdbd08ebf4b.json

ingress:
  - hostname: api.somaping.online
    service: http://localhost:8000
  - hostname: geo.somaping.online
    service: http://localhost:8080
  - hostname: nominatim.somaping.online
    service: http://localhost:8088
  - service: http_status:404